@startuml
'https://plantuml.com/sequence-diagram

' Activation style
' Activation style
skinparam sequence {
    ArrowColor DeepSkyBlue
    ActorBorderColor DeepSkyBlue
    LifeLineBorderColor DeepSkyBlue
}

actor MainLaby

MainLaby -> MoteurJeu: main(String[] args)
activate MoteurJeu
create LabyJeu
MainLaby -> LabyJeu : LabyJeu()
create LabyDessin
MainLaby -> LabyDessin: LabyDessin()
activate LabyDessin
MoteurJeu -> LabyDessin: dessinJeu(LabyJeu, canvas)
LabyDessin --> MoteurJeu
deactivate LabyDessin
MoteurJeu -> LabyJeu: init()
activate LabyJeu
LabyJeu --> MoteurJeu
MoteurJeu -> LabyJeu: setTaille(width, height)
MoteurJeu <-- LabyJeu
MoteurJeu -> LabyJeu: setFPS(pFPS)
MoteurJeu <-- LabyJeu
MoteurJeu -> LabyJeu: update(double secondes, clavier)
MoteurJeu <-- LabyJeu
deactivate LabyJeu
MainLaby <-- MoteurJeu:
deactivate MoteurJeu

@enduml