@startuml
'https://plantuml.com/sequence-diagram

skinparam sequence {
    ArrowColor DeepSkyBlue
    ActorBorderColor DeepSkyBlue
    LifeLineBorderColor DeepSkyBlue
}


MoteurJeu->MoteurJeu : button.addEventHandler()
note right
clique sur un boutton d'attaque/soin
end note
MoteurJeu->Combat : attaque(int codeAttaque)
MoteurJeu<--Combat :

@enduml