@startuml
participant "MoteurJeu" as moteurJeu
participant "Labyrinthe" as labyrinthe
participant "Serpent" as serpent
participant "Element:ArrayList<Element>" as element

moteurJeu -> labyrinthe: deplacerSerpent()
activate labyrinthe
labyrinthe -> serpent: getX(), getY()
activate serpent
labyrinthe -> serpent: getCorp()
activate serpent
loop ième élément
    serpent -> element: etrePresent(x, y)
    activate element
    element --> serpent: true
    deactivate element

end
serpent --> labyrinthe
labyrinthe --> moteurJeu
deactivate serpent
deactivate labyrinthe
@enduml
